export const PRODUCTS: string[] = [
    'Apple',
    'Banana',
    'Cherry',
    'Date',
    'Elderberry',
    'Fig',
    'Grape',
    'Honeydew',
    'Indian Prune',
    'Jackfruit',
    'Kiwi',
    'Lemon',
    'Mango',
]